env:
 development:
  database:
   name: golangvietnam_develop
   host: 127.0.0.1
   port: 27017
   user: ""
   password: ""
  server:
   host: localhost
   port: 8080
 production:
  database:
   name: golangvietnam_production
   host: 127.0.0.1
   port: 27017
   user: ""
   password: ""
  server:
   host: 127.0.0.1
   port: 8080
 testing:
  database:
   name: golangvietnam_test
   host: 127.0.0.1
   port: 27017
   user: ""
   password: ""
  server:
   host: 127.0.0.1
   port: 5000
secret: co_chi_mo_ma_coi